language: go

install:
    - sudo apt-get install ninja-build

script:
    - go test ./...
    - mkdir stage
    - cd stage 
    - ../bootstrap.bash
    - ninja
    - diff -us ../build.ninja.in .bootstrap/bootstrap.ninja.in
    - ../tests/test.sh
