language: go

cache:
    directories:
        - $HOME/ninjabin

install:
    - ./.travis.install-ninja.sh
    - export PATH=$PATH:~/ninjabin

before_script:
    - source .travis.fix-fork.sh

script:
    - go test ./...
    - cp build.ninja.in build.ninja.in.orig
    - mkdir stage
    - cd stage 
    - ../bootstrap.bash
    - ninja
    - diff -us ../build.ninja.in ../build.ninja.in.orig
